version: "3.9"

services:
  database:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: mobiledev
      POSTGRES_USER: mobiledev
      POSTGRES_PASSWORD: mobiledev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
