CREATE TABLE folder
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    folder_name VARCHAR(255),
    user_id     BIGINT,
    chat_id     BIGINT,
    CONSTRAINT pk_folder PRIMARY KEY (id)
);

ALTER TABLE folder
    ADD CONSTRAINT FK_FOLDER_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);

ALTER TABLE folder
    ADD CONSTRAINT FK_FOLDER_ON_USER FOREIGN KEY (user_id) REFERENCES workflow."user" (id);