CREATE TABLE message
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id           BIGINT,
    user_id           BIGINT,
    message_status_id BIGINT,
    content_text      VARCHAR(255),
    deleted           BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_MESSAGE_STATUS FOREIGN KEY (message_status_id) REFERENCES message_status (id);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_USER FOREIGN KEY (user_id) REFERENCES workflow."user" (id);