CREATE TABLE favorite
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT,
    favorite_chat_id BIGINT,
    CONSTRAINT pk_favorite PRIMARY KEY (id)
);

ALTER TABLE favorite
    ADD CONSTRAINT FK_FAVORITE_ON_FAVORITE_CHAT FOREIGN KEY (favorite_chat_id) REFERENCES chat (id);

ALTER TABLE favorite
    ADD CONSTRAINT FK_FAVORITE_ON_USER FOREIGN KEY (user_id) REFERENCES workflow."user" (id);