CREATE TABLE workflow."user"
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login     VARCHAR(255),
    password  VARCHAR(255),
    full_name VARCHAR(255),
    media_id  BIGINT,
    phone     VARCHAR(255),
    email     VARCHAR(255),
    role_id   BIGINT,
    deleted   BOOLEAN,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE workflow."user"
    ADD CONSTRAINT FK_USER_ON_MEDIA FOREIGN KEY (media_id) REFERENCES media (id);

ALTER TABLE workflow."user"
    ADD CONSTRAINT FK_USER_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);