CREATE TABLE chat_permission
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT,
    chat_id          BIGINT,
    deleting_enabled BOOLEAN,
    CONSTRAINT pk_chat_permission PRIMARY KEY (id)
);

ALTER TABLE chat_permission
    ADD CONSTRAINT FK_CHAT_PERMISSION_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);

ALTER TABLE chat_permission
    ADD CONSTRAINT FK_CHAT_PERMISSION_ON_USER FOREIGN KEY (user_id) REFERENCES workflow."user" (id);