CREATE TABLE role_connection
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT,
    chat_id          BIGINT,
    role_id          BIGINT,
    deleting_enabled BOOLEAN,
    CONSTRAINT pk_role_connection PRIMARY KEY (id)
);

ALTER TABLE role_connection
    ADD CONSTRAINT FK_ROLE_CONNECTION_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);

ALTER TABLE role_connection
    ADD CONSTRAINT FK_ROLE_CONNECTION_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE role_connection
    ADD CONSTRAINT FK_ROLE_CONNECTION_ON_USER FOREIGN KEY (user_id) REFERENCES workflow."user" (id);